---
title: "Analyse data nback"
author: "Francesco Pupillo"
date: "1/4/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)# select comes from this
library(ggplot2)
library(gridExtra)
library(gplots)
library(stringr)



```


```{r message=FALSE, warning=FALSE, include=FALSE}
# get participants number
setwd("clean_data")

participants<-list.files()

# loop through the files and check the practice trials
# initialise an empty dataframe, with subject number, trialN, accuracy, cumacc
nBackAll<-vector()

for (p in participants){
  
  files<-list.files(p)
  file<-read.csv(paste0(p, "/", substr(p, 5,6), "_nBack.csv"))
  
  #substr the letters of the response
  file$response<-substr(file$key_resp_4.keys, 3,3)
  
  # change the correct response for violin, cheer, obsession, as it was wrong
  # during list creation (note that cheer is repeated)
  words<-c("violin", "cheer", "obsession")
  for (w in words){
    if (w=="cheer"){
      file$CORRanswer[file$word==w][4]<-"l"
    } else{
      file$CORRanswer[file$word==w][2]<-"l"
    }
  }
  
  # calculate accuracy again
  file$accuracy<-ifelse(file$response==file$CORRanswer,1,0)
  
  # general accuracy
  accuracy<-sum(  file$accuracy)/nrow(file)
  
  # hit rate
  hits<-sum( file$accuracy[file$hit_NoHit=="Hit"])
  hitRate<-mean( file$accuracy[file$hit_NoHit=="Hit"])
  
  corrRej<-sum( file$accuracy[file$hit_NoHit=="NoHit"])

  # FA
  fa<-sum( file$accuracy[file$hit_NoHit=="NoHit"]==0)
  faRate<-sum( file$accuracy[file$hit_NoHit=="NoHit"]==0)/ length( file$accuracy[file$hit_NoHit=="NoHit"])
  
  # Miss
  miss<-sum( file$accuracy[file$hit_NoHit=="Hit"]==0)

  participant<-substr(p, 5,6)
  
  # # reaction times. Clean the variable
  file$key_resp_4.rt<-as.character(file$key_resp_4.rt)
  
  file$RT<-substr(file$key_resp_4.rt, 2, nchar(file$key_resp_4.rt)-1)
  
  file$RT<-as.numeric(file$RT)
  
  # now only for correct ones
  RTcorr<-mean(file$RT[file$accuracy==1])
  
  df<-as.data.frame(cbind(participant, accuracy, hits, corrRej, fa, miss,
                          hitRate, faRate,RTcorr))
  
  nBackAll<-rbind(nBackAll, df)
  }


```

### Table with nBack performance
```{r, echo=FALSE}
knitr::kable(nBackAll,format= "simple", digits=2)

# write down info
write.csv(recogData[,c("participant", "FA", "HIT", "Miss", "presInEnc", "listN", 
                          "HITrate", "FArate", "dprime", "hitMinFA")],
          "/users/francesco/PowerFolders/MemLear/2_Analysis_Folder/group_data/all.nback.csv", row.names=F)
```



```
